### ISSUE TITLE
[Security Issue] Exposure of Encryption Secret Key

### ISSUE THREAD

**Issue by smtdfc** [thanhcong2k7/fuchsiaVN#2]
[Security Issue] Exposure of Encryption Secret Key

Hello,

I want to bring to your attention a potential security issue found in this repository. In the file `login/login.php` (line 41), there is a concern regarding the exposure of a secret key used for encryption.

### Issues Identified:
1. **Fixed IV Usage**: The initialization vector (IV) used for AES-128-CTR is hardcoded, which compromises the security of the encryption. Using a static IV can make the encryption predictable and vulnerable to attacks.

2. **Sensitive Information Exposure**: If the password used for encryption or the data being encrypted is exposed, it may lead to unauthorized access to sensitive information.

3. **Storage of Sensitive Data in Cookies**: Storing sensitive data in cookies increases the risk of exposure, especially if these cookies are not transmitted over secure channels (HTTPS).

### Suggested Fixes:
**Implement Random IV**: Use a randomly generated IV for each encryption operation. Here is a code snippet to illustrate the change:

   ```php
   // Generate a random IV for encryption
   $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('AES-128-CTR'));
   // Encrypt the data
   $encrypted_value = openssl_encrypt($key, "AES-128-CTR", $pwd, 0, $iv);
   // Store both IV and encrypted value in the cookie
   setcookie("saveses", base64_encode($iv . $encrypted_value), time() + (86400 * 30), "/");
```

Thank you, and I hope this helps improve the security of your project.

Best regards,
smtdfc team

**Comment by thanhcong2k7** [comment]
Hi there! Thanks for pointing out the potential issue in my code! This is my first time trying encrypting sensitive data in my code, so I just simply put a string there (as I don't really understand how it worked) to demonstrate the functionality of being automatically logged in without re-submit the login form again (the "Remember me" checkbox).
Once again, thanks for the help!
